language: go
os:
  - windows
  - linux
go:
  - "1.11.x"
  - "1.12.x"
  - "1.x"
  - master
env:
  - GO111MODULE=on
matrix:
  allow_failures:
    - os: windows
      go: master
before_install:
- git lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ffmpeg; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then sed -i 's\TestFFmpegWrapper_downloadStop\FFmpegWrapper_downloadStop\' vigoler/ffmpeg_wrapper_test.go; fi
